added format selecter to yt-video.sh

diff --git a/yt-video b/yt-video
--- a/yt-video
+++ b/yt-video
@@ -1,4 +1,6 @@
 #!/bin/bash
+
+#check for dependancies
 cd ~/
 if ! command -v screen &> /dev/null
 then
@@ -22,11 +24,12 @@ echo "Please run install-deps.sh"
         exit
 fi
 
+#set default dir
 FILE=~/.ytdlvideo.conf
 if [ -f "$FILE" ]; then
         change=$(sed -n -e 3p $FILE)
 else
-read -p "Input directory you want to save video files to (Use full path name ex: /home/YOURUSERNAME/Downloads): " rootdir
+read -p "Input directory you want to save video files to by default (Use full path name ex: /home/YOURUSERNAME/Downloads): " rootdir
 cat <<EOF > $FILE
 #this file was made to ensure that yt-dlp knows where to save your videos
 #edit this directory if you with to change it
@@ -35,6 +38,8 @@ EOF
 change=$(sed -n -e 3p $FILE)
 fi
 cd $change
+
+#ask for new folder
 while true
 do
         read -r -p "Do you want to add a directory to put your vidoe(s) in? [Y/n] " input
@@ -53,6 +58,46 @@ do
                 ;;
         esac
 done
+
+#get url and filename
 echo input youtube url.
 read url
-screen -mS "yt-dlp" yt-dlp --format mp4 $url
+filename=$(yt-dlp --restrict-filenames --get-filename $url)
+
+#execute download
+screen -mS "yt-dlp" yt-dlp --restrict-filenames $url
+clear
+
+#select video format
+echo 'Choose your option below, to continue:
+1 mkv (same quality as original)
+2 mov (same quality as original)
+3 mp4 (same quality as original)
+4 mp4 (compressed)
+5 webp (original download)'
+# Function for $errors:
+function error {
+  echo -e "\\e[91m$1\\e[39m"
+  exit 1
+}
+read number && echo "selected"
+case $number in
+    1)
+	ffmpeg -i $filename -vcodec copy -acodec copy $filename.mkv
+	;;
+    2)
+	ffmpeg -i $filename -vcodec copy -acodec copy $filename.mov
+	;;
+    3)
+	ffmpeg -i $filename -vcodec copy -acodec copy $filename.mp4
+	;;
+    4)
+	read -p "Input compression quality 0-51 (0 being no compression, 51 being max compression, 23 being default) " compress
+	ffmpeg -i $filename -vcodec libx264 -crf $compress filename.mp4
+	;;
+    5)
+	echo "webp selected"
+	exit
+	;;
+    *)	echo "invalid option '$number'";;
+esac
